[package]
name = "_cs336_a1_rust"
version = "0.1.0"
edition = "2024"

[lib]
name = "_cs336_a1_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module"] }